apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: todo-grpc
  namespace: todo-grpc
  labels:
    app: todo-grpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-grpc
  template:
    metadata:
      labels:
        app: todo-grpc
    spec:
      containers:
      - name: todo-grpc
        image: dnivra26/todo_grpc:0.1
        ports:
          - containerPort: 7777
            protocol: TCP
            name: grpc
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: todo-grpc-postgresql.default
          - name: todo_grpc_hello_host
            value: todo-grpc-hello.todo-grpc-hello
          - name: todo_grpc_hello_port
            value: "7778"
      - name: envoy
        image: envoyproxy/envoy:latest
        ports:
          - containerPort: 9901
            protocol: TCP
            name: envoy-admin
          - containerPort: 8787
            protocol: TCP
            name: envoy-grpc
        volumeMounts:
          - name: envoy-config-volume
            mountPath: /etc/envoy-config/
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy-config/config.yaml", "--v2-config-only", "-l", "debug","--service-cluster","cluster","--service-node","node"]
      volumes:
        - name: envoy-config-volume
          configMap:
            name: envoy-config
            items:
              - key: config
                path: config.yaml